runtime: python311

service: abc-jobs-gateway

entrypoint: uvicorn main:app --port 8081
#entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: F2

env_variables:
    CANDIDATES_MS: url_no_protocol

vpc_access_connector:
    name: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME
    egress_setting: all-traffic
